{
 "title": "Sidekiq Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sidekiq_processes" }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sidekiq_busy_workers" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes{name=~\"issue-37_metrics_1\"}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sidekiq_workers" }
   ]
  },
  {
   "title": "Queues latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_queue_latency_seconds[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Max Processing Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sidekiq_queue_max_processing_time_seconds"
    }
   ]
  },
  {
   "title": "Queue enqueued jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sidekiq_queue_enqueued_jobs", "legendFormat": "{{name}}" }
   ]
  }
 ]
}